### ISSUE TITLE
Is there a pre-trained editing model for StyleGAN2

### ISSUE THREAD

**Issue by lbc402** [yhlleo/stylegan-mmuit#1]
I don't see a pre-trained editing model for testing, can it be released?

**Comment by lbc402** [comment]
What is the meaning of “use_vae” parameter https://github.com/yhlleo/stylegan-mmuit/blob/master/styleganv2/core/solver.py#L105

**Comment by yhlleo** [comment]
Hi @lbc402 , I updated the [README.md](https://github.com/yhlleo/stylegan-mmuit/blob/master/styleganv2/README.md). You can find the uploaded pretrained model and usage.

For the  "use_vae", I deleted it from the codes. 

Any questions are welcome!
